// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import IconsSprite from "@/utils/icons-sprite";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <IconsSprite />
        <Header/>
        {children}
        <Footer/>        
      </body>
    </html>
  );
}
